# Generated by Django 4.2.5 on 2023-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="roomName",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
